/* 3840x2160: Modeline "3840x2160" 533.6 3840 3982 4027 4064 2160 2170 2180 2190 +hsync +vsync */
#define HSYNC_POL 1
#define VSYNC_POL 1
#define YPULSE (63+10)
#define XPULSE 45
#define YPIX 2160
#define XPIX 3840
#define VFREQ 60
#define DPI 96
#define CLOCK 533600
#define VERSION 1
#define REVISION 3
#define XOFFSET 142
#define YOFFSET (63+10)
#define XY_RATIO XY_RATIO_16_9
#define YBLANK 30
#define XBLANK 224
#define TIMING_NAME "3840x2160"
#include "edid.S"
